# Generated by Django 4.2.16 on 2024-10-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria_usuario_subcategoria_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='presupuesto_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
