# Generated by Django 4.2.16 on 2024-10-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0004_alter_categoria_usuario_alter_subcategoria_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso')], default='Gasto', max_length=10),
        ),
    ]
